'use strict';
const root=document.querySelector('#app');let step=0;
const docs=[['Electronic signature consent','consent'],['Prime participant release','release'],['Rental agreement','rental']];
function show(){
 if(step===0){root.innerHTML=`<section class="hero"><div><span class="eyebrow">JET SKI MIAMI 7 · SIGNING PREVIEW</span><h1>Less paperwork.<br>More blue.</h1><p class="muted">A simple mobile check-in. Your own documents, one clear step at a time.</p><div class="actions"><button id="next">Explore the guest experience →</button></div><p class="help">This public preview uses a fictional booking. The full signing backend is undergoing final activation checks.</p></div><div class="ocean"><span class="eyebrow">BEFORE YOU ARRIVE</span><strong>Ocean time.</strong><p>Check your details. Read at your pace. Choose to sign each document.</p></div></section>`}
 else if(step===1){root.innerHTML=`<div class="narrow"><span class="eyebrow">1 OF 3 · YOUR DETAILS</span><h1>Let's get you checked in.</h1><div class="card"><span class="pill">Fictional booking DEMO-REVIEW</span><h2>Alex Example</h2><div class="grid"><p><strong>Your ride</strong><br>September 10, 2026 · 10:00 AM</p><p><strong>Your group</strong><br>1 adult · 1 demo PWC</p><p><strong>Email</strong><br>alex@example.invalid</p><p><strong>Emergency contact</strong><br>Jamie Example</p></div><p class="help">In the live platform, booking details are prefilled from SmartRez. Each adult confirms their own contact information. Staff verifies the complete roster and vessel assignment.</p><div class="actions"><button id="next">Continue to the sample documents →</button><button class="secondary" id="back">Back</button></div></div></div>`}
 else if(step<5){const [name,code]=docs[step-2];root.innerHTML=`<div class="narrow"><span class="eyebrow">2 OF 3 · READ & SIGN</span><h1>One document<br>at a time.</h1><div class="card"><span class="pill">Sample ${step-1} of 3</span><h2>${name}</h2><p>Open the complete sample PDF, including its demonstration signing certificate.</p><a class="doc-link" target="_blank" rel="noopener" href="examples/${code}_sample.pdf">Open sample PDF ↗</a><p class="help">The live platform presents the exact document, records your explicit decision to sign, and saves an individual PDF with evidence. Each instrument is separate. You can reuse your drawn signature only by explicitly adopting it again.</p><label class="check"><input type="checkbox" id="read"><span>I understand this is a demonstration using fictional data. This does not sign a real agreement.</span></label><div class="actions"><button id="next">Continue the preview →</button><button class="secondary" id="back">Back</button></div></div></div>`}
 else{root.innerHTML=`<div class="narrow"><span class="eyebrow">3 OF 3 · AT THE DOCK</span><h1>Less to do.<br>More to look forward to.</h1><div class="card"><div class="complete-icon">✓</div><h2>That is the online flow.</h2><p>The real service saves each signed PDF and queues a copy by email. At the dock, your instructor confirms identity, safety credentials, equipment, the complete roster and the actual on-water check ride.</p><p>The FWC instruction form opens only after instruction and is signed separately by the instructor and the participant.</p><p class="warning">This demonstration has not checked in a real guest or authorized a launch.</p>${docs.map(([name,code])=>`<div class="document-row"><span>${name}</span><a href="examples/${code}_sample.pdf" target="_blank" rel="noopener">Sample PDF ↗</a></div>`).join('')}<div class="actions"><button id="restart">Start again</button></div></div></div>`}
 document.querySelector('#next')?.addEventListener('click',()=>{if(step>=2&&step<5&&!document.querySelector('#read').checked){document.querySelector('#read').focus();return}step++;show();window.scrollTo(0,0)});document.querySelector('#back')?.addEventListener('click',()=>{step--;show()});document.querySelector('#restart')?.addEventListener('click',()=>{step=0;show();window.scrollTo(0,0)});
}show();
